# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: run metrics collector script in background
  ansible.builtin.shell:
    cmd: "nohup /opt/collect_metrics.py > /opt/metrics.log 2>&1 &"
  args:
    chdir: /opt
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "/opt/networkagent.json"
  async: 15 # A short async timeout is fine here as nohup and '&' handle the backgrounding
  poll: 0 # Tell Ansible to start and move on immediately
