apiVersion: apps/v1
kind: Deployment
metadata:
  name: ageviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ageviewer
  template:
    metadata:
      labels:
        app: ageviewer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - services
      containers:
        - name: ageviewer
          image: localhost:5001/ageviewer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ageviewer
  labels:
    app: ageviewer
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: ageviewer